# # Stage !: Build angular app
FROM node:alpine as build

COPY ./ /app
WORKDIR /app
RUN npm ci
RUN npm run build --omit=dev


# Stage 2: Serve app with nginx server
FROM nginx:alpine

COPY --from=build /app/dist/meta-parameter-optimizer /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ng.conf /etc/nginx/conf.d/
COPY --from=build /app/node_modules/@hpcc-js/wasm/dist/graphvizlib.wasm /usr/share/nginx/html/assets/@hpcc-js/wasm/dist/graphvizlib.wasm
EXPOSE 80
